# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0925b32b86e4850204886d6a2e035f45"
name = "ai store builder 2"
application_url = "https://pulse-commerce-ai.netlify.app"
embedded = false

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_content"
optional_scopes = [ ]
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://pulse-commerce-ai.netlify.app/api/shopify/oauth/callback"
]
